### ISSUE TITLE
convert_weight.py  

### ISSUE THREAD

**Issue by kalayan** [OpenSourceAI/yolov3_tensorflow_Chinese#3]
小白想问一下您convert_weight.py是做什么的呢？

请问一下这时候要怎么办呢？谢谢！我是想用coco的预训练模型训练VOC训练集，得到模型再训练别的训练集。好像不convert_weight 的话不行

**Comment by chenquan** [comment]
@onexming 你有空看一下这个问题.

**Comment by Follow-spaceX** [comment]
convert_weight.py把darknet训练生成的.wight权重文件读出来，转换成tensorflow模型参数，也就是 tf.train.Saver(restore_dict)，然后保存生成.ckpt 或者 *.pb
